// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-panel/AdminPanel.tsx": () => import("../components/mockups/admin-panel/AdminPanel.tsx")
};
